export const THEME = {
  teal: "#008080",
  orange: "#FFA500",
  black: "#0A0A0A",
};

export const PERFORMANCE_THRESHOLDS = {
  high: 0.75,
  low: 0.35,
};

export const STATES_DISTRICTS = [
  { state: "Andhra Pradesh", districts: ["Anakapalli", "Anantapur", "Chittoor"] },
  { state: "Bihar", districts: ["Patna", "Gaya", "Muzaffarpur"] },
  { state: "Delhi", districts: ["New Delhi"] },
  { state: "Karnataka", districts: ["Bengaluru Urban", "Mysuru", "Belagavi"] },
  { state: "Maharashtra", districts: ["Mumbai", "Pune", "Nagpur"] },
  { state: "Rajasthan", districts: ["Jaipur", "Udaipur", "Jodhpur"] },
  { state: "Uttar Pradesh", districts: ["Lucknow", "Varanasi", "Kanpur Nagar"] },
];

export const MP_DISTRICTS = [
  "Agar Malwa",
  "Alirajpur",
  "Anuppur",
  "Ashoknagar",
  "Balaghat",
  "Barwani",
  "Betul",
  "Bhind",
  "Bhopal",
  "Burhanpur",
  "Chhatarpur",
  "Chhindwara",
  "Damoh",
  "Datia",
  "Dewas",
  "Dhar",
  "Dindori",
  "Guna",
  "Gwalior",
  "Harda",
  "Hoshangabad",
  "Indore",
  "Jabalpur",
  "Jhabua",
  "Katni",
  "Khandwa",
  "Khargone",
  "Mandla",
  "Mandsaur",
  "Morena",
  "Narsinghpur",
  "Neemuch",
  "Panna",
  "Raisen",
  "Rajgarh",
  "Ratlam",
  "Rewa",
  "Sagar",
  "Satna",
  "Sehore",
  "Seoni",
  "Shahdol",
  "Shajapur",
  "Sheopur",
  "Shivpuri",
  "Sidhi",
  "Singrauli",
  "Tikamgarh",
  "Ujjain",
  "Umaria",
  "Vidisha",
  "Niwari",
];
